require('dotenv').config({ path: __dirname + '/.env' });

module.exports = {
  apps: [
    {
      name: 'aklab-api',
      cwd: __dirname + '/api',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      health_check: {
        url: 'http://localhost:1338/_health',
        interval: 15000,
        timeout: 5000,
        retries: 3,
      },
      env: {
        ...process.env,
        PORT: process.env.PORT_API || 1338,
      },
    },
    {
      name: 'aklab-app',
      cwd: __dirname + '/app',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        PORT: process.env.PORT_APP || 5174,
      },
    },
    // ─────────────────────────────────────────────────────────────────
    // Микросервисы (dev)
    // ─────────────────────────────────────────────────────────────────
    {
      name: 'aklab-parser-fabrikant-dev',
      cwd: __dirname + '/services/parser-fabrikant',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1345',
        SERVICE_NAME: 'parser-fabrikant',
        QUEUE_NAME: 'parse-fabrikant',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-torgi-gov-dev',
      cwd: __dirname + '/services/parser-torgi-gov',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1346',
        SERVICE_NAME: 'parser-torgi-gov',
        QUEUE_NAME: 'parse-torgi-gov',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-analyzer-dev',
      cwd: __dirname + '/services/analyzer',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-digest-dev',
      cwd: __dirname + '/services/digest',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
        EMAIL_SMTP_HOST: process.env.EMAIL_SMTP_HOST || 'smtp.yandex.ru',
        EMAIL_SMTP_PORT: process.env.EMAIL_SMTP_PORT || '465',
        EMAIL_SMTP_USER: process.env.EMAIL_SMTP_USER || '',
        EMAIL_SMTP_PASS: process.env.EMAIL_SMTP_PASS || '',
        EMAIL_DEFAULT_FROM: process.env.EMAIL_DEFAULT_FROM || '',
      },
    },
    {
      name: 'aklab-parser-aggregator-bankrot-dev',
      cwd: __dirname + '/services/parser-aggregator-bankrot',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1348',
        SERVICE_NAME: 'parser-aggregator-bankrot',
        QUEUE_NAME: 'parse-aggregator-bankrot',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-alfalot-dev',
      cwd: __dirname + '/services/parser-alfalot',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1349',
        SERVICE_NAME: 'parser-alfalot',
        QUEUE_NAME: 'parse-alfalot',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-etprf-dev',
      cwd: __dirname + '/services/parser-etprf',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1350',
        SERVICE_NAME: 'parser-etprf',
        QUEUE_NAME: 'parse-etprf',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-sberbank-ast-dev',
      cwd: __dirname + '/services/parser-sberbank-ast',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1351',
        SERVICE_NAME: 'parser-sberbank-ast',
        QUEUE_NAME: 'parse-sberbank-ast',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-invest-mosreg-dev',
      cwd: __dirname + '/services/parser-invest-mosreg',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1352',
        SERVICE_NAME: 'parser-invest-mosreg',
        QUEUE_NAME: 'parse-invest-mosreg',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-investmoscow-dev',
      cwd: __dirname + '/services/parser-investmoscow',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1353',
        SERVICE_NAME: 'parser-investmoscow',
        QUEUE_NAME: 'parse-investmoscow',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-roseltorg-dev',
      cwd: __dirname + '/services/parser-roseltorg',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1354',
        SERVICE_NAME: 'parser-roseltorg',
        QUEUE_NAME: 'parse-roseltorg',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-m-ets-dev',
      cwd: __dirname + '/services/parser-m-ets',
      script: 'npm',
      args: 'run dev',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'development',
        PORT: '1355',
        SERVICE_NAME: 'parser-m-ets',
        QUEUE_NAME: 'parse-m-ets',
        QUEUE_DB_PATH: __dirname + '/queue.db',
        STRAPI_URL: 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
  ],
};
