require('dotenv').config({ path: __dirname + '/.env' });

module.exports = {
  apps: [
    {
      name: 'aklab-api',
      cwd: '/home/rudin/aklab/api',
      script: 'node',
      args: 'node_modules/@strapi/strapi/bin/strapi.js start',
      interpreter: 'none',
      health_check: {
        url: 'http://localhost:1338/_health',
        interval: 15000,
        timeout: 5000,
        retries: 3,
      },
      env: {
        ...process.env,
        PORT: process.env.PORT_API,
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      },
    },
    {
      name: 'aklab-app',
      cwd: '/home/rudin/aklab/app',
      script: 'npm',
      args: 'run preview -- --host',
      interpreter: 'none',
      env: {
        ...process.env,
        PORT: process.env.PORT_APP,
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      },
    },
    // ─────────────────────────────────────────────────────────────────
    // Микросервисы (prod)
    // ─────────────────────────────────────────────────────────────────
    {
      name: 'aklab-parser-fabrikant',
      cwd: '/home/rudin/aklab/services/parser-fabrikant',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'production',
        PORT: '1345',
        SERVICE_NAME: 'parser-fabrikant',
        QUEUE_NAME: 'parse-fabrikant',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-torgi-gov',
      cwd: '/home/rudin/aklab/services/parser-torgi-gov',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'production',
        PORT: '1346',
        SERVICE_NAME: 'parser-torgi-gov',
        QUEUE_NAME: 'parse-torgi-gov',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-analyzer-prod',
      cwd: '/home/rudin/aklab/services/analyzer',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-digest-prod',
      cwd: '/home/rudin/aklab/services/digest',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      env: {
        ...process.env,
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
        EMAIL_SMTP_HOST: process.env.EMAIL_SMTP_HOST || 'smtp.yandex.ru',
        EMAIL_SMTP_PORT: process.env.EMAIL_SMTP_PORT || '465',
        EMAIL_SMTP_USER: process.env.EMAIL_SMTP_USER || '',
        EMAIL_SMTP_PASS: process.env.EMAIL_SMTP_PASS || '',
        EMAIL_DEFAULT_FROM: process.env.EMAIL_DEFAULT_FROM || '',
      },
    },
  ],
};