require('dotenv').config({ path: __dirname + '/.env' });

module.exports = {
  apps: [
    {
      name: 'aklab-api',
      cwd: '/home/rudin/aklab/api',
      script: 'node',
      args: 'node_modules/@strapi/strapi/bin/strapi.js start',
      interpreter: 'none',
      max_memory_restart: '768M',
      exp_backoff_restart_delay: 100,
      health_check: {
        url: 'http://localhost:1338/_health',
        interval: 15000,
        timeout: 5000,
        retries: 3,
      },
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        HOST: process.env.HOST || '0.0.0.0',
        PORT: process.env.PORT_API || '1338',
        PUBLIC_URL: process.env.PUBLIC_URL || '',
        APP_KEYS: process.env.APP_KEYS || '',
        API_TOKEN_SALT: process.env.API_TOKEN_SALT || '',
        ADMIN_JWT_SECRET: process.env.ADMIN_JWT_SECRET || '',
        TRANSFER_TOKEN_SALT: process.env.TRANSFER_TOKEN_SALT || '',
        ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || '',
        JWT_SECRET: process.env.JWT_SECRET || '',
        DATABASE_FILENAME: process.env.DATABASE_FILENAME || '',
        STRAPI_ADMIN_EMAIL: process.env.STRAPI_ADMIN_EMAIL || '',
        STRAPI_ADMIN_PASSWORD: process.env.STRAPI_ADMIN_PASSWORD || '',
      },
    },
    {
      name: 'aklab-app',
      cwd: '/home/rudin/aklab/app',
      script: 'npm',
      args: 'run preview -- --host',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: process.env.PORT_APP || '4173',
      },
    },
    // ─────────────────────────────────────────────────────────────────
    // Микросервисы (prod)
    // ─────────────────────────────────────────────────────────────────
    {
      name: 'aklab-parser-fabrikant',
      cwd: '/home/rudin/aklab/services/parser-fabrikant',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1345',
        SERVICE_NAME: 'parser-fabrikant',
        QUEUE_NAME: 'parse-fabrikant',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-torgi-gov',
      cwd: '/home/rudin/aklab/services/parser-torgi-gov',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1346',
        SERVICE_NAME: 'parser-torgi-gov',
        QUEUE_NAME: 'parse-torgi-gov',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-analyzer-prod',
      cwd: '/home/rudin/aklab/services/analyzer',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-digest-prod',
      cwd: '/home/rudin/aklab/services/digest',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
        EMAIL_SMTP_HOST: process.env.EMAIL_SMTP_HOST || 'smtp.yandex.ru',
        EMAIL_SMTP_PORT: process.env.EMAIL_SMTP_PORT || '465',
        EMAIL_SMTP_USER: process.env.EMAIL_SMTP_USER || '',
        EMAIL_SMTP_PASS: process.env.EMAIL_SMTP_PASS || '',
        EMAIL_DEFAULT_FROM: process.env.EMAIL_DEFAULT_FROM || '',
      },
    },
    {
      name: 'aklab-photo-fetcher-prod',
      cwd: '/home/rudin/aklab/services/photo-fetcher',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1356',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-aggregator-bankrot',
      cwd: '/home/rudin/aklab/services/parser-aggregator-bankrot',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1348',
        SERVICE_NAME: 'parser-aggregator-bankrot',
        QUEUE_NAME: 'parse-aggregator-bankrot',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-alfalot',
      cwd: '/home/rudin/aklab/services/parser-alfalot',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1349',
        SERVICE_NAME: 'parser-alfalot',
        QUEUE_NAME: 'parse-alfalot',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-etprf',
      cwd: '/home/rudin/aklab/services/parser-etprf',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1350',
        SERVICE_NAME: 'parser-etprf',
        QUEUE_NAME: 'parse-etprf',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-sberbank-ast',
      cwd: '/home/rudin/aklab/services/parser-sberbank-ast',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1351',
        SERVICE_NAME: 'parser-sberbank-ast',
        QUEUE_NAME: 'parse-sberbank-ast',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-invest-mosreg',
      cwd: '/home/rudin/aklab/services/parser-invest-mosreg',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1352',
        SERVICE_NAME: 'parser-invest-mosreg',
        QUEUE_NAME: 'parse-invest-mosreg',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-investmoscow',
      cwd: '/home/rudin/aklab/services/parser-investmoscow',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1353',
        SERVICE_NAME: 'parser-investmoscow',
        QUEUE_NAME: 'parse-investmoscow',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-roseltorg',
      cwd: '/home/rudin/aklab/services/parser-roseltorg',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1354',
        SERVICE_NAME: 'parser-roseltorg',
        QUEUE_NAME: 'parse-roseltorg',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
    {
      name: 'aklab-parser-m-ets',
      cwd: '/home/rudin/aklab/services/parser-m-ets',
      script: 'node',
      args: 'dist/index.js',
      interpreter: 'none',
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        NVM_DIR: '/home/rudin/.nvm',
        PATH: '/home/rudin/.nvm/versions/node/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        PORT: '1355',
        SERVICE_NAME: 'parser-m-ets',
        QUEUE_NAME: 'parse-m-ets',
        QUEUE_DB_PATH: '/home/rudin/aklab/queue.db',
        STRAPI_URL: process.env.STRAPI_INTERNAL_URL || 'http://localhost:1338',
        STRAPI_API_TOKEN: process.env.STRAPI_API_TOKEN || '',
      },
    },
  ],
};
